/**
 * @brief Flash registers
 */

#include "registers/helpers.h"

#pragma once

#define FLASH_BASE 0x40022000

#define FLASH_ACR_OFFSET       0x00000000
#define FLASH_RSVD_OFFSET      0x00000004
#define FLASH_KEYR_OFFSET      0x00000008
#define FLASH_OPTKEYR_OFFSET   0x0000000C
#define FLASH_SR_OFFSET        0x00000010
#define FLASH_CR_OFFSET        0x00000014
#define FLASH_ECCR_OFFSE       0x00000018
#define FLASH_OPTR_OFFSET      0x00000020
#define FLASH_PCROP1ASR_OFFSET 0x00000024
#define FLASH_PCROP1AER_OFFSET 0x00000028
#define FLASH_WRP1AR_OFFSET    0x0000002C
#define FLASH_WRP1BR_OFFSET    0x00000030
#define FLASH_PCROP1BSR_OFFSET 0x00000034
#define FLASH_PCROP1BER_OFFSET 0x00000038
#define FLASH_PCROP2ASR_OFFSET 0x00000044
#define FLASH_PCROP2AER_OFFSET 0x00000048
#define FLASH_WRP2AR_OFFSET    0x0000004C
#define FLASH_WPR2BR_OFFSET    0x00000050
#define FLASH_PCROP2BSR_OFFSET 0x00000054
#define FLASH_PCROP2BER_OFFSET 0x00000058
#define FLASH_SECR_OFFSET      0x00000080


#define FLASH_ACR       REGISTER(FLASH_BASE + FLASH_ACR_OFFSET)
#define FLASH_RSVD      REGISTER(FLASH_BASE + FLASH_RSVD_OFFSET)
#define FLASH_KEYR      REGISTER(FLASH_BASE + FLASH_KEYR_OFFSET)
#define FLASH_OPTKEYR   REGISTER(FLASH_BASE + FLASH_OPTKEYR_OFFSET)
#define FLASH_SR        REGISTER(FLASH_BASE + FLASH_SR_OFFSET)
#define FLASH_CR        REGISTER(FLASH_BASE + FLASH_CR_OFFSET)
#define FLASH_ECCR      REGISTER(FLASH_BASE + FLASH_ECCR_OFFSET)
#define FLASH_OPTR      REGISTER(FLASH_BASE + FLASH_OPTR_OFFSET)
#define FLASH_PCROP1ASR REGISTER(FLASH_BASE + FLASH_PCROP1ASR_OFFSET)
#define FLASH_PCROP1AER REGISTER(FLASH_BASE + FLASH_PCROP1AER_OFFSET)
#define FLASH_WRP1AR    REGISTER(FLASH_BASE + FLASH_WRP1AR_OFFSET)
#define FLASH_WRP1BR    REGISTER(FLASH_BASE + FLASH_WRP1BR_OFFSET)
#define FLASH_PCROP1BSR REGISTER(FLASH_BASE + FLASH_PCROP1BSR_OFFSET)
#define FLASH_PCROP1BER REGISTER(FLASH_BASE + FLASH_PCROP1BER_OFFSET)
#define FLASH_PCROP2ASR REGISTER(FLASH_BASE + FLASH_PCROP2ASR_OFFSET)
#define FLASH_PCROP2AER REGISTER(FLASH_BASE + FLASH_PCROP2AER_OFFSET)
#define FLASH_WRP2AR    REGISTER(FLASH_BASE + FLASH_WRP2AR_OFFSET)
#define FLASH_WPR2BR    REGISTER(FLASH_BASE + FLASH_WPR2BR_OFFSET)
#define FLASH_PCROP2BSR REGISTER(FLASH_BASE + FLASH_PCROP2BSR_OFFSET)
#define FLASH_PCROP2BER REGISTER(FLASH_BASE + FLASH_PCROP2BER_OFFSET)
#define FLASH_SECR      REGISTER(FLASH_BASE + FLASH_SECR_OFFSET)

