/**
 * @brief PD PHY Registers
 */

#include "registers/helpers.h"

#pragma once

#define PD1_BASE 0x4000A000
#define PD2_BASE 0x4000A400

#define PD_CFG1_OFFSET       0x00000000
#define PD_CFG2_OFFSET       0x00000004
#define PD_CFG3_OFFSET       0x00000008
#define PD_CR_OFFSET         0x0000000C
#define PD_IMR_OFFSET        0x00000010
#define PD_SR_OFFSET         0x00000014
#define PD_ICR_OFFSET        0x00000018
#define PD_TX_ORDSET_OFFSET  0x0000001C
#define PD_TX_PAYSZ_OFFSET   0x00000020
#define PD_TXDR_OFFSET       0x00000024
#define PD_RX_ORDSET_OFFSET  0x00000028
#define PD_RX_PAYSZ_OFFSET   0x0000002C
#define PD_RXDR_OFFSET       0x00000030
#define PD_RX_ORDEXT1_OFFSET 0x00000034
#define PD_RX_ORDEXT2_OFFSET 0x00000038


#define PD1_CFG1       REGISTER(PD1_BASE + PD_CFG1_OFFSET)
#define PD1_CFG2       REGISTER(PD1_BASE + PD_CFG2_OFFSET)
#define PD1_CFG3       REGISTER(PD1_BASE + PD_CFG3_OFFSET)
#define PD1_CR         REGISTER(PD1_BASE + PD_CR_OFFSET)
#define PD1_IMR        REGISTER(PD1_BASE + PD_IMR_OFFSET)
#define PD1_SR         REGISTER(PD1_BASE + PD_SR_OFFSET)
#define PD1_ICR        REGISTER(PD1_BASE + PD_ICR_OFFSET)
#define PD1_TX_ORDSET  REGISTER(PD1_BASE + PD_TX_ORDSET_OFFSET)
#define PD1_TX_PAYSZ   REGISTER(PD1_BASE + PD_TX_PAYSZ_OFFSET)
#define PD1_TXDR       REGISTER(PD1_BASE + PD_TXDR_OFFSET)
#define PD1_RX_ORDSET  REGISTER(PD1_BASE + PD_RX_ORDSET_OFFSET)
#define PD1_RX_PAYSZ   REGISTER(PD1_BASE + PD_RX_PAYSZ_OFFSET)
#define PD1_RXDR       REGISTER(PD1_BASE + PD_RXDR_OFFSET)
#define PD1_RX_ORDEXT1 REGISTER(PD1_BASE + PD_RX_ORDEXT1_OFFSET)
#define PD1_RX_ORDEXT2 REGISTER(PD1_BASE + PD_RX_ORDEXT2_OFFSET)


#define PD2_CFG1       REGISTER(PD2_BASE + PD_CFG1_OFFSET)
#define PD2_CFG2       REGISTER(PD2_BASE + PD_CFG2_OFFSET)
#define PD2_CFG3       REGISTER(PD2_BASE + PD_CFG3_OFFSET)
#define PD2_CR         REGISTER(PD2_BASE + PD_CR_OFFSET)
#define PD2_IMR        REGISTER(PD2_BASE + PD_IMR_OFFSET)
#define PD2_SR         REGISTER(PD2_BASE + PD_SR_OFFSET)
#define PD2_ICR        REGISTER(PD2_BASE + PD_ICR_OFFSET)
#define PD2_TX_ORDSET  REGISTER(PD2_BASE + PD_TX_ORDSET_OFFSET)
#define PD2_TX_PAYSZ   REGISTER(PD2_BASE + PD_TX_PAYSZ_OFFSET)
#define PD2_TXDR       REGISTER(PD2_BASE + PD_TXDR_OFFSET)
#define PD2_RX_ORDSET  REGISTER(PD2_BASE + PD_RX_ORDSET_OFFSET)
#define PD2_RX_PAYSZ   REGISTER(PD2_BASE + PD_RX_PAYSZ_OFFSET)
#define PD2_RXDR       REGISTER(PD2_BASE + PD_RXDR_OFFSET)
#define PD2_RX_ORDEXT1 REGISTER(PD2_BASE + PD_RX_ORDEXT1_OFFSET)
#define PD2_RX_ORDEXT2 REGISTER(PD2_BASE + PD_RX_ORDEXT2_OFFSET)

